# docker-compose run autobdd-run "--project ${BDD_PROJECT}"
# 
version: '3.5'
services:
  example-dev:
    image: "xyteam/autobdd-dev:${AutoBDD_Ver}"
    container_name: ${BDD_PROJECT}-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects/${BDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}:rw
    ports:
      - "5901:5900"
      - "2222:22"
    environment:
      BDD_PROJECT: ${BDD_PROJECT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      VNC_PASSWORD: ${VNC_PASSWORD}
      RESOLUTION: 1920x1200x24
    entrypoint: ["/bin/bash", "/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}/docker/autobdd-dev.startup.sh"]

  example-run:
    image: "xyteam/autobdd-run:${AutoBDD_Ver}"
    container_name: ${BDD_PROJECT}-run
    shm_size: 2048M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects/${BDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}:rw
    environment:
      USER: ${USER}
      BDD_PROJECT: ${BDD_PROJECT}
      HOSTOS: ${HOSTOS}
      USERID: ${USERID}
      GROUPID: ${GROUPID}
    entrypoint: ["/bin/bash", "/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}/docker/autobdd-run.startup.sh"]
